apiVersion: v1
kind: Service
metadata:
  name: api-external
  namespace: keptn
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30333
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: api
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}